api.go
api_test.go
fakes/fake_service_broker.go
service_broker.go

The Services API has mandatory parameters for unbind/deprovision - this PR parses them and passes them into `Unbind` and `Deprovision`. Therefore it does extend the function signature for these two methods.

unbind/deprovision parses incoming service_id/plan_id parameters

---

api.go
api_test.go
service_broker.go

This allows consumers to decode the params to their own custom structs

Expose the raw JSON parameters of a provisioning request

---

api_test.go
fakes/fake_service_broker.go
fixtures/binding_with_volume_mounts.json
service_broker.go

see: http://docs.cloudfoundry.org/services/api.html#binding and http://docs.cloudfoundry.org/services/api.html#binding
this api isn't stable yet, so there will be another one of these PRs, but we're pointing at this fork for now and would love to be back on master :)

add volume mounts as per 2.9 service broker api spec

---

README.md

Edited:
Since Cloud Controller checks whether service plans can be updated
before calling the service broker, the `ErrPlanChangeNotSupported` error
is redundant.
* Drop `ErrPlanChangeNotSupported` error
* Add missing errors to docs

Drop redundant error type.

---

api.go
api_test.go
fixtures/binding_with_experimental_volume_mounts.json
response.go

When the broker API version header is 2.9, we transform the broker's 2.10-style binding response into a 2.9 experimental one when volume mounts are present.
Notes
1. We map `volume_id` onto `group_id`, as the UUIDs are identical in the API docs, although this probably coincidence!
1. We JSON-marshal the `mount_config` object returned by the broker. We weren't sure what encoding to use to squash this into a string, but JSON seemed reasonable.
What do you think @avade and @lwoydziak ?
Cheers,
@ablease and Craig

Support experimental volume mount binding response API

---

api.go
api_test.go

I have a broker with an asynchronous deprovision and according to [the broker API docs](https://docs.cloudfoundry.org/services/api.html#polling), the broker should return a 410 from `lastOperation` once the instance is gone. I'm returning `brokerapi.ErrInstanceDoesNotExist` in my code but that's being translated into a 404 not a 410. This means cloud foundry never removes the service from its database and it continues to be listed by `cf services`. This change fixes that issue. 
I don't know if there was a particular reason to return 404 before but if there is, just let me know and I'll find another solution to this problem. Also, I couldn't find any docs about contributing to this project so apologies if I'm missing something. Please just let me know if you'd like me to do anything …

LastOperation should return 410 when the instance doesn't exist

---

api_test.go
catalog.go
fakes/fake_service_broker.go
fixtures/catalog.json
service_broker.go

This pull request adds two things which were introduced in the [OpenServiceBroker API version 2.13](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md) :
1. Allow access the values provided in the "context" parameter for provision and bind requests
2. Allow specifying the various Schema objects in the service plans returned in the catalog

Make the library more compatible with the OpenServiceBroker API specification

---

catalog.go
catalog_test.go

- allow to add custom field in the plan that can be retrieved from
catalog endpoint
Signed-off-by: Carlo Colombo <ccolombo@pivotal.io>

AdditionalMetadata field in plan and service metadata

---

Gopkg.lock
api.go
api_test.go
catalog_test.go
fakes/fake_service_broker.go
fixtures/async_bind_response.json
response.go
response_test.go
service_broker.go

This PR adds support in the library for implementing brokers which support the OSB 2.14 async. bind operations.
It adds an ``async`` parameter to the Bind callback, and adds the ``lastOperation`` for bindings and ``getBinding`` endpoints to the ``ServiceBroker`` interface.

Add support for async. bind operations

---

api.go
api_test.go
catalog_test.go
failure_response_test.go
fakes/fake_service_broker.go
fixtures/get_instance.json
response.go
response_test.go
service_broker.go

Added:
1. Support for the GetService endpoint (https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#fetching-a-service-instance) 
2. Support for allowing the broker to get an updated dashboard-url in update operations ( https://github.com/openservicebrokerapi/servicebroker/pull/437 ).
I think that with these two pieces, the brokerapi library supports OSB version 2.14 .

Add missing pieces for supporting OSB 2.14 

---

README.md
api.go

Adds middleware that parse the `https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#originating-identity` and adds it as a value to the downstream context.
Initially considered adding it to the structs details structs that are passed to service broker methods, but some requests (such as the catalog request) don't take any params other than the context.
Advice on testing this appropriately would be appreciated.

Add limited support for Originating Identity

---

README.md
api.go
context_utils.go
context_utils_test.go

As discussed in proposal pivotal-cf/brokerapi#62 .
- Adds utility functions for adding and retrieving `Service` and `ServicePlan` objects to `context.Context`
- Adds tests for utility functions
- When provision endpoint is called, adds found service and plans to request context
- Updates documentation with an example

Add found Service and ServicePlan to context

---

api.go
api_test.go
middlewares/info_location_header.go

Add infoLocation to context. This will allow to ping back the platform and obtain additional details if required.

Capture  X-Api-Info-Location header in all broker requests

---

Gopkg.lock
Gopkg.toml

Ginkgo and Gomega produce regular versions, so it's
more reproducible to use version numbers than to work
off master. A version bumper (like Dependabot) can be
used to stay up to date.
code.cloudfoundry.org/lager does not seem to produce
regular versions, so it makes sense to keep working off
master for this dependency.

Use releases of Gomega and Ginkgo rather than master

---

api_test.go
domain/service_broker.go
fakes/fake_service_broker.go
handlers/bind.go
handlers/provision.go

I have the same use case as in [issue](https://github.com/pivotal-cf/brokerapi/issues/69).
Added:
- Provision handler returns status 200 OK if an instance is already present
- Bind handler returns status 200 OK if a binding is already present
Pull request:

Return statusOK when resource exists

---

handlers/api_handler.go

When returning binding information from the broker, connection strings containing ampersands and other HTML escapable characters arrive escaped to PCF.
We recommend disabling the HTML escape in the JSON encoding process.

Disables HTML encoding for JSON responses

---

Gopkg.lock
api.go
api_test.go
handlers/api_handler.go
handlers/bind.go
handlers/deprovision.go
handlers/get_binding.go
handlers/get_instance.go
handlers/last_binding_operation.go
handlers/last_binding_operation_test.go
handlers/last_operation.go
handlers/provision.go
handlers/unbind.go
handlers/update.go
middlewares/api_version_header.go
middlewares/correlation_id_header.go

Fixes #81.
Added:
- Correlation id middleware
Pull request:

Add correlation id middleware

---

handlers/bind.go
handlers/deprovision.go
handlers/get_binding.go
handlers/get_instance.go
handlers/last_binding_operation.go
handlers/last_operation.go
handlers/provision.go
handlers/unbind.go
handlers/update.go
utils/context.go
utils/context_test.go

My colleague @ataleksandrov recently contributed [this PR](https://github.com/pivotal-cf/brokerapi/pull/82) where a correlation/request ID is added to the request context. Then in every OSB operation handler, that ID is added as a data property to the logger.
Unfortunately, we've noticed that if one uses [`AttachRoutes`](https://github.com/pivotal-cf/brokerapi/blob/master/api.go#L50) instead of [`New`](https://github.com/pivotal-cf/brokerapi/blob/master/api.go#L33) for its broker, the [correlation ID middleware](https://github.com/pivotal-cf/brokerapi/blob/master/middlewares/correlation_id_header.go) is never "attached" (like every other middleware, it should be explicitly added).
That results in `nil` pointer error when trying to cast the correlation ID, which is `nil`, to `string` in …

Fix logger data enrichment

---

api_test.go
domain/service_broker.go

**Description** 
- Add GetRawParameters method on UpdateDetails struct
Currently, I'm not able to use the `DetailsWithRawContext` interface properly, because the `UpdateDetails` does not implement the required method.
```
// Invoking this method is not possible with UpdateDetails struct
func Foo(details DetailsWithRawParameters) {
raw := details.GetRawParameters()
// ...
}
```
Signed-off-by: Mateusz Szostok <szostok.mateusz@gmail.com>

Add GetRawContext method on UpdateDetails struct

---

domain/service_catalog.go
domain/service_catalog_test.go
go.mod
v7/domain/service_catalog.go

Per spec we should be able to set the maximum_polling duration on the ServicePlan https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-plan-object
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#polling-interval-and-duration

feat: maximum_polling_duration was missing from ServicePlan

---

domain/apiresponses/responses.go
domain/apiresponses/responses_test.go
domain/service_broker.go
handlers/provision.go

Hi,
This PR adds an optional `metadata` field to the `ProvisioningResponse` according to the [specification](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-4)
Problem mentioned before in this [issue](https://github.com/pivotal-cf/brokerapi/issues/128)

Add metadata parameter to provisioning response body

---

api_test.go
fakes/fake_service_broker.go
handlers/bind.go
handlers/catalog.go
handlers/deprovision.go
handlers/get_binding.go
handlers/get_instance.go
handlers/last_binding_operation.go
handlers/last_operation.go
handlers/provision.go
handlers/unbind.go
handlers/update.go
middlewares/context_keys.go
middlewares/correlation_id_header.go
middlewares/info_location_header.go
middlewares/originating_identity_header.go
middlewares/request_identity_header.go
staticcheck.conf
utils/context.go
utils/context_test.go

The documentation for context.WithValue() says that:
> The provided key must be comparable and should not be of type string
or any other built-in type to avoid collisions between packages using
context.
https://golang.org/pkg/context/#WithValue
Updated to use derived types for context value keys, which are all
exported as constants so that users can import the constant to access
the values.
CorrelationIDKey and RequestIdentityKey were already exported constants, so users
who imported and used these constants should not experience a breaking change.
BREAKING CHANGE

fix: use non-string types for context value keys

---

handlers/bind.go
handlers/deprovision.go
handlers/get_binding.go
handlers/get_instance.go
handlers/last_binding_operation.go
handlers/last_operation.go
handlers/provision.go
handlers/unbind.go
handlers/update.go

PR #148 started to read this header, but the value was not logged. To be
consistent with the correlation ID header (which is logged) we should
log the request ID too.
Note that correlation ID will be logged as `correlation-id` and request identity will be logged as `requestIdentity`. This is inconsistent, and would be much easier to tidy up after #155 is merged, because it introduces consistent use of a constant.

fix: log 'X-Broker-API-Request-Identity' header value

---

domain/apiresponses/responses.go
domain/apiresponses/responses_test.go
domain/service_broker.go
handlers/get_instance.go
handlers/update.go

Hi,
This PR adds an optional `metadata` field to the `FetchingResponse` and `UpdatingResponse` according to the specification for [Fetching a Service Instance](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-5) and [Updating a Service Instance](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-7)
It is a similar solution as for `ProvisioningResponse` in [this PR](https://github.com/pivotal-cf/brokerapi/pull/131)

Add metadata parameter to get and update response body

---

api.go
api_test.go
auth/auth.go

This commit provides the necessary means for projects building upon the
brokerapi to use their own authentication middleware, e.g. to provide
authentication based on Bearer tokens as defined in RFC 6750,
section 2.1.
Closes #158

Support custom authentication middleware implementations

---

api.go
api_options.go
api_test.go

This is an example of how #177 could be implemented by using the options pattern in the constructor

Allow URL-encoded paths via options pattern

---

README.md
api.go
api_options.go
api_test.go
go.mod
go.sum
handlers/bind.go
handlers/deprovision.go
handlers/get_binding.go
handlers/get_instance.go
handlers/last_binding_operation.go
handlers/last_binding_operation_test.go
handlers/last_operation.go
handlers/provision.go
handlers/unbind.go
handlers/update.go

gorilla/mux has been archived as a project, and it's preferable to depend on a maintained HTTP handler. go-chi/chi is the closest fit for gorilla/mux and appears to be well used and maintained.
An additional breaking change is that go-chi/chi will ignore URL-encoded slashes for routing purposes, so PUT /v2/service_instances/foo%2Fbar will treat "foo%2Fbar" as an instance ID and will not try to route to /v2/service_instances/foo/bar as the gorilla/mux version would have done by default. Previously the WithEncodedPath() option was used to configure gorilla/mux to treat "foo%2Fbar" as an instance ID, but as this is now the default, WithEncodedPath() option has been removed. Treating "foo%2Fbar" as foo/bar is not an option with go-chi/chi.

feat!: swap gorilla/mux for go-chi/chi

---

domain/apiresponses/failure_responses.go
domain/apiresponses/failure_responses_test.go
failure_response.go
failure_response_test.go

The function NewFailureResponse() creates an error. The [Go FAQ](https://go.dev/doc/faq#nil_error) says:
> It's a good idea for functions that return errors always to use the error type in their signature (as we did above) rather than a concrete type such as *MyError, to help guarantee the error is created correctly. As an example, os.Open returns an error even though, if not nil, it's always of concrete type *os.PathError.
Returning the concrete type can result in subtle failures. For example, consider the code:
```go
func something() error {
var err *apiresponses.FailureResponse
if 1 != 1 {
err = apiresponses.NewFailureResponse(errors.New("something bad has happened with the universe"), http.StatusInternalServerError, "log-key")
}
return err
}
func main() {
if err := something(); err != …
```

fix: NewFailureResponse() should return type error

---

.github/workflows/run-tests.yml
go.mod

[#185100152](https://www.pivotaltracker.com/story/show/185100152)

chore: limit support of Go versions to 1.20 & 1.21

---

.github/workflows/run-tests.yml

If stable is provided, action will get the latest stable version from the go-versions repository manifest.
If oldstable is provided, when current release is 1.19.x, action will resolve version as 1.18.x, where x is the latest patch release.
We also want to maintain 1.20 version, so we test it.
[#186180915](https://www.pivotaltracker.com/story/show/186180915)

test: using stable/oldstable aliases

---

api_options.go
api_test.go

Allows custom middleware to be added *after* the default middleware.
Resolves https://github.com/pivotal-cf/brokerapi/issues/273

feat: WithAdditionalMiddleware() option

---

domain/service_metadata.go
domain/service_metadata_test.go
domain/service_plan_metadata.go

Some unhandled errors are now handled. Arguably this is not necessary as they are "impossible" errors that cannot occur and are untestable. But code can change over time, and if those errors ever become possible, then it will be better to fail fast rather than to ignore the error.

chore: handle some unhandled errors

---

api_test.go
go.mod
go.sum

This dependency has not been updated in 6 years. It's used only in tests, adds minimal value to this project, and any dependency is a potential security risk.

chore: drop the github.com/drewolson/testflight dependency

---

api_test.go
catalog_test.go
domain/apiresponses/failure_responses.go
domain/apiresponses/responses.go
domain/service_broker.go
domain/service_catalog.go
domain/service_metadata.go
domain/service_metadata_test.go
domain/service_plan_metadata.go
domain/service_plan_metadata_test.go
fakes/fake_service_broker.go
handlers/api_handler.go
handlers/get_instance.go
handlers/provision.go
handlers/update.go

In Go, "any" was introduced alongside generics because the empty interface "interface{}" was considered a bit confusing. They mean the same thing, and code with "any" is a bit easier to understand and looks more modern. Test fakes were not updated as they are generated code.

chore: prefer "any" to "interface{}"

---

api_suite_test.go
fixtures/invalid_async_provision_error.json

Uses the Go embed functonality to access the test fixtures, and has the useful side-effect of removing the last usage of the deprecated "ioutil" package. Also an unused test fixture was removed.

test: improve loading of test fixtures

---

domain/apiresponses/responses_test.go
domain/service_broker.go

Change for InstanceMetadata maps to follow OSB specification: https://github.com/openservicebrokerapi/servicebroker/blob/v2.17/spec.md#service-instance-metadata
To allow key-value pairs, not only key-value string pair

Allow any value type in InstanceMetadata maps

---

domain/apiresponses/responses.go
domain/service_broker.go
handlers/bind.go
handlers/get_binding.go

The [Open Service Broker API](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md) defines an endpoint object in the [GET Binding Response](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#binding) that is not defined in the brokerapi response. This pull request adds an endpoint struct and updates the GetBindingReponse and GetBindingSpec to properly support the endpoints object.

fix: adds endpoint to support get-binding response for OSB v2.16

---

domain/apiresponses/responses.go
domain/service_broker.go
handlers/bind.go
handlers/get_binding.go

According to OSB API Spec, the Binding Object contains a Metadata Object with `expires_at` and `renew_before` which are missing in the current implementation. `expires_at` was introduces in OSB API [2.16](https://github.com/openservicebrokerapi/servicebroker/blob/master/release-notes.md#v216) and `renew_before` in [2.17](https://github.com/openservicebrokerapi/servicebroker/blob/master/release-notes.md#v217).

fix: Add expiration date and time for bindings

---

.github/workflows/run-tests.yml
go.mod
go.sum

We should support all in-support Go versions. An update to Counterfieter and a bug in our CI has resulted in us accidentally dropping Go 1.22 support.

chore: re-support Go 1.22

---

.github/workflows/run-tests.yml

We deliberately test against a matrix of Go versions, but Go toolchain changes mean that the version of Go is being upgraded on the fly, so for example the Go 1.21 test actually uses Go 1.23. This is confusing and not the desired behavior.

test: prevent upgrade of Go version

---

.github/workflows/run-tests.yml
go.mod

Go 1.22 is no longer in active support.
Removed use of stable and oldstable alias due to oldstable resolving to an out of support version

chore: Drop support for go 1.22

---

README.md

We have neglected the README and some links and text have become outdated.

docs: update README links and text

---

catalog_test.go
domain/service_broker.go
domain/service_catalog.go
domain/service_metadata.go
domain/service_metadata_test.go
domain/service_plan_metadata.go
domain/service_plan_metadata_test.go
fakes/fake_service_broker.go

The modernize command replaces old constructs with simpler, updated ones.
Command is:
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...

chore: apply fixes from Go modernize command
